tg_token = "your_telegram_bot_token"
db_path = "../deque.sqlite"
release = false
admin_ids = 0
max_jobs = 100
format = "Вечерний вопрос. Можно ответить или пропустить.\n\n%s"
location = "Europe/Moscow"
default_time = "20:00"
chat_id = 0
